line-length = 120
target-version = "py311"

# keep noisy dirs out globally
exclude = [
  "outputs/**",
  "logs/**",
  ".venv/**", "venv/**", "env/**",
  "**/*.bak",
]

[lint]
select = ["E","F","W","I"]

[lint.per-file-ignores]
"scripts/yacc.py" = ["E731","E741"]