[mypy]
disable_error_code = import-untyped
python_version = 3.13
ignore_missing_imports = True
warn_unused_ignores = True
no_implicit_optional = True
disallow_untyped_defs = False
follow_imports = silent

# Exclude junk & backups
exclude = (?x)^(?:\.venv|venv|build|dist|\.eggs|\.git|backups|scripts)(/|\\|$)
install_types = False




