[tool.ruff]
line-length = 100
target-version = "py311"

[tool.black]
line-length = 100
extend-exclude = '(?x)(^(backups|outputs|scripts)(/|\\)|_BACKUP_|^remove_emoji_from_prints\.py$|^agents(/|\\)meta(/|\\)magic_patch\.py$)'
