# MAGIC Week1 shim for BeautifulSoup4 imports
class FakeBS4:
    class builder: ...
    class element: ...
    class dammit: ...
    class _typing: ...
    class _deprecation: ...
bs4 = FakeBS4()
__all__ = ["bs4", "FakeBS4"]
