#!/usr/bin/env python
"""
MAGIC – Auto Script Generator (FORCE OVERWRITE MODE)

This version:

- Scans the `scripts/` tree for files ending in `_READY.py`.
- ALWAYS writes a new boilerplate implementation into each file.
- Before overwriting, it creates a backup copy of the original file under:

    outputs/backups/generator_full_overwrite_<TIMESTAMP>/<relative_path>

So your original content is never lost – you can always restore from backups.
"""

import datetime as _dt
import shutil
from pathlib import Path
from typing import Dict, Any, Optional, Tuple, List


PHASE_NAMES: Dict[int, str] = {
    0: "IGNITE – Bootstrap Core",
    1: "FOUNDATION – Architecture",
    2: "ZEPHYR – Trend Forecasting",
    3: "SCRIBE – Content Generation",
    4: "VISTA – Dashboard Layer",
    5: "PRISM – Multimedia Generation",
    6: "NEXUS – Distribution Engine",
    7: "MIDAS – Monetization Engine",
    8: "AURA – Analytics Engine",
    9: "OVERSEER – Orchestration",
    10: "BEACON – SEO Traffic Layer",
    11: "SHIELD – Audit & Fortification",
    12: "LOOP – UGC Feedback Layer",
    13: "FLOW – Affiliate Funnels",
    14: "VANTAGE – Decision Engine",
    15: "PULSE – Real-Time Alerts",
    16: "HAVEN – Community Layer",
    17: "OMEGA – Failover & Recovery",
}

AUTO_HEADER_MARKER = "MAGIC Auto-Generated Script"
GEN_LOG_RELATIVE = Path("outputs/logs/magic_generate_magic_scripts.log")


def _detect_project_root() -> Path:
    here = Path(__file__).resolve()
    tools_dir = here.parent
    root = tools_dir.parent
    return root


def _extract_phase_module(path: Path) -> Tuple[Optional[int], Optional[str]]:
    phase_num: Optional[int] = None
    module_letter: Optional[str] = None

    for part in path.parts:
        if part.lower().startswith("phase"):
            try:
                phase_num = int(part[5:])
            except ValueError:
                pass

    for part in path.parts:
        if part.lower().startswith("module_"):
            module_letter = part.split("_", 1)[1].upper()
            break

    return phase_num, module_letter


def _render_boilerplate(
    rel_path: Path,
    phase_num: Optional[int],
    module_letter: Optional[str],
) -> str:
    filename = rel_path.name

    if phase_num is not None:
        phase_name = PHASE_NAMES.get(phase_num, "Unknown Phase")
        phase_str = f"{phase_num} – {phase_name}"
    else:
        phase_str = "Unknown"

    module_str = module_letter or "Unknown"
    now = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines: List[str] = []

    lines.append('"""')
    lines.append(AUTO_HEADER_MARKER)
    lines.append("")
    lines.append("This file was generated by tools/generate_magic_scripts.py")
    lines.append(f"on {now}.")
    lines.append("")
    lines.append("You can safely edit the `run()` function to add real logic.")
    lines.append("The self-healing runner and orchestrators will treat this file")
    lines.append("as a standard MAGIC script.")
    lines.append("")
    lines.append(f"Phase: {phase_str}")
    lines.append(f"Module: {module_str}")
    lines.append(f"Relative path: {rel_path.as_posix()}")
    lines.append('"""')
    lines.append("")
    lines.append("from typing import Any, Dict, Optional")
    lines.append("")
    lines.append("")
    lines.append("def run(context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:")
    lines.append('    """')
    lines.append("    Main entrypoint for MAGIC.")
    lines.append("")
    lines.append("    Parameters")
    lines.append("    ----------")
    lines.append("    context:")
    lines.append("        Optional shared context dictionary passed by orchestrators or")
    lines.append("        the self-healing runner. You can use this to pass configuration")
    lines.append("        or state between scripts.")
    lines.append("")
    lines.append("    Returns")
    lines.append("    -------")
    lines.append("    Dict[str, Any]")
    lines.append("        A JSON-serializable dictionary with at least:")
    lines.append('        - status: \"OK\" | \"WARN\" | \"ERROR\"')
    lines.append("        - message: short human-readable description")
    lines.append("        - phase / module / script: identifiers for logging")
    lines.append('    """')
    lines.append("    if context is None:")
    lines.append("        context = {}")
    lines.append("")
    lines.append("    result: Dict[str, Any] = {")
    lines.append('        "status": "OK",')
    lines.append('        "message": "Auto-generated placeholder. Implement me with real MAGIC logic.",')

    if phase_num is not None:
        lines.append(f'        "phase": {phase_num},')
    else:
        lines.append('        "phase": None,')

    lines.append(f'        "module": {module_str!r},')
    lines.append(f'        "script": {filename!r},')
    lines.append('        "context_keys": sorted(context.keys()),')
    lines.append("    }")
    lines.append("")
    lines.append("    # TODO: Replace this block with real behaviour.")
    lines.append("    # For example:")
    lines.append("    # - analyse inputs in context")
    lines.append("    # - read/write from outputs/")
    lines.append("    # - emit metrics for analytics")
    lines.append("    # - interact with external services via helpers")
    lines.append("    return result")
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    import json")
    lines.append("    print(json.dumps(run(), indent=2))")
    lines.append("")

    return "\n".join(lines)


def _append_log(root: Path, line: str) -> None:
    log_path = root / GEN_LOG_RELATIVE
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("a", encoding="utf-8") as fh:
        fh.write(line + "\n")


def main() -> None:
    root = _detect_project_root()
    scripts_dir = root / "scripts"

    if not scripts_dir.is_dir():
        raise SystemExit(f"Could not find scripts/ under {root}")

    timestamp = _dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_root = root / "outputs" / "backups" / f"generator_full_overwrite_{timestamp}"
    backup_root.mkdir(parents=True, exist_ok=True)

    total = 0
    changed = 0
    backup_errors = 0
    write_errors = 0

    for py_file in scripts_dir.rglob("*_READY.py"):
        total += 1
        rel = py_file.relative_to(root)

        backup_path = backup_root / rel
        try:
            backup_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(py_file, backup_path)
            _append_log(root, f"[BACKUP] {rel} -> {backup_path.relative_to(root)}")
        except OSError as exc:
            backup_errors += 1
            _append_log(root, f"[ERROR:backup] {rel}: {exc}")

        phase_num, module_letter = _extract_phase_module(py_file)
        boilerplate = _render_boilerplate(rel, phase_num, module_letter)

        try:
            py_file.write_text(boilerplate, encoding="utf-8", newline="\n")
            changed += 1
            _append_log(root, f"[WRITE] {rel}")
        except OSError as exc:
            write_errors += 1
            _append_log(root, f"[ERROR:write] {rel}: {exc}")

    summary = (
        f"Total _READY.py files seen: {total} | "
        f"Overwritten: {changed} | "
        f"Backup errors: {backup_errors} | "
        f"Write errors: {write_errors} | "
        f"Backup root: outputs/backups/generator_full_overwrite_{timestamp}"
    )
    _append_log(root, "[SUMMARY] " + summary)
    print(summary)


if __name__ == "__main__":
    main()
