name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - chore/restore-ci
      - '**'

permissions:
  contents: read

jobs:
  tests:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install test deps
        shell: pwsh
        run: |
          python -m pip install -U pip
          if (Test-Path requirements-dev.txt) { pip install -r requirements-dev.txt }
          pip install pytest
      - name: Run tests
        shell: pwsh
        run: pytest -q