name: CI
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    name: tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }
      - name: Install deps
        run: |
          python -m pip install -U pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          if (Test-Path requirements-dev.txt) { pip install -r requirements-dev.txt }
          pip install pytest
      - name: Run tests
        run: pytest -q

  mypy:
    name: mypy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }
      - name: Install type deps
        run: |
          python -m pip install -U pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install mypy
      - name: Type check
        run: mypy .
