name: CI

jobs:
  mypy:
    name: mypy
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install mypy + stubs
        shell: pwsh
        run: |
          python -m pip install -U pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install mypy types-requests
      - name: Type check
        shell: pwsh
        run: python -m mypy --config-file mypy.ini tools

  tests:
    name: tests
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install -U pip
          if (Test-Path requirements.txt)     { pip install -r requirements.txt }
          if (Test-Path requirements-dev.txt) { pip install -r requirements-dev.txt }
          pip install --upgrade --only-binary=:all: numpy pandas matplotlib
          pip install pytest
      - name: Run tests
        shell: pwsh
        run: pytest -q
