name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -U pip
      - run: pip install pre-commit pytest pytest-cov
      - name: Lint & type-check
        run: pre-commit run --all-files
      - name: Tests with coverage
        run: pytest -q --maxfail=1 --disable-warnings --cov=tools --cov-branch --cov-report=xml:coverage.xml --cov-report=term-missing --cov-fail-under=90
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: true
