name: CI

on:
  push:
    branches: [ "main", "fix/mypy-e2e-67" ]
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: Tests + coverage (tools only)
        run: |
          pytest -q --maxfail=1 --disable-warnings 
            --cov=tools --cov-branch 
            --cov-report=xml:coverage.xml --cov-report=term

      - name: Upload coverage.xml (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: error

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          verbose: true
          fail_ci_if_error: true
