name: CI
on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - run: python -m pip install --upgrade pip

      - name: Install project deps (if present)
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Install dev deps (if present)
        if: hashFiles('requirements-dev.txt') != ''
        run: pip install -r requirements-dev.txt

      - run: pip install pytest pytest-cov

      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings --cov=tools --cov-branch --cov-report=xml --cov-fail-under=90

      - uses: codecov/codecov-action@v4
        if: always()
        with:
          files: ./coverage.xml
          fail_ci_if_error: false