name: CI
on:
  pull_request:
  push:
permissions:
  contents: read
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          if (Test-Path requirements-dev.txt) { pip install -r requirements-dev.txt }
          pip install pytest pre-commit mypy ruff

      - name: Pre-commit
        shell: pwsh
        run: pre-commit run --all-files

      - name: Pytest
        shell: pwsh
        run: pytest -q