name: CI
on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  runner-dry-run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Dry run self-healing runner (Phase 11 / Module B)
        shell: pwsh
        run: |
          if (Test-Path .\phase_manifest.json) {
            python .\self_healing_runner_v4.8_fixed.py --manifest .\phase_manifest.json --phases 11 --modules B --dry-run
          } else {
            Write-Host "phase_manifest.json not found — skipping dry run"
          }
