name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main, chore/**, feature/** ]

permissions:
  contents: read
  id-token: write   # needed if we use Codecov OIDC

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest coverage codecov

      - name: Run fast tests with coverage (tools only)
        run: |
          pytest -q --maxfail=1 --disable-warnings 
            --cov=tools --cov-branch 
            --cov-report=xml --cov-report=term-missing 
            --cov-fail-under=90

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          use_oidc: true   # works if the Codecov GitHub App is installed for this repo
