name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # dev deps (pytest, coverage)
          pip install pytest pytest-cov

      - name: Run tests with coverage (80% gate)
        run: |
          pytest -o addopts="--cov --cov-report=term --cov-report=html --cov-fail-under=80" -q

      - name: Upload coverage html
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
