name: mypy

on:
  workflow_dispatch:
  push:
    paths:
      - 'tools/**'
      - 'mypy.ini'
      - '.github/workflows/mypy.yml'
  pull_request:
    paths:
      - 'tools/**'
      - 'mypy.ini'
      - '.github/workflows/mypy.yml'

jobs:
  mypy:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install type deps
        shell: pwsh
        run: |
          python -m pip install -U pip
          if (Test-Path requirements.txt)     { pip install -r requirements.txt }
          if (Test-Path requirements-dev.txt) { pip install -r requirements-dev.txt }
          pip install mypy
          # Missing stubs for requests:
          pip install types-requests
      - name: Type check
        shell: pwsh
        run: |
          python -m mypy --config-file mypy.ini tools