on:
  pull_request:
    paths:
      - "**/*.py"
      - "tools/**"
      - "tests/**"
      - "pyproject.toml"
      - "setup.cfg"
      - "setup.py"
      - "requirements*.txt"
  push:
    branches: [ main ]
    paths:
      - "**/*.py"
      - "tools/**"
      - "tests/**"
      - "pyproject.toml"
      - "setup.cfg"
      - "setup.py"
      - "requirements*.txt"
  workflow_dispatch:

name: Python application
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest .\scripts

