name: self-heal

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CI smoke
        run: echo "self-heal pass"
