name: self-heal

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sanity
        run: |
          echo "self-heal / ci is alive ✅"
