name: self-heal
on:
  pull_request:
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  job:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - run: echo 'placeholder for required check: self-heal / ci'
